version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "80:80"
    links:
      - redis:redis
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    expose:
      - "6379"
